language: python
before_script:
  - pip install tox
script:
  - tox
matrix:
  fast_finish: true
  allow_failures:
    - env: TOXENV=docstrings
  include:
    - python: 3.7
      env: TOXENV=py37
    - python: 3.7
      env: TOXENV=py37
      dist: xenial
      group: edge
      virt: lxd
      sudo: true

notifications:
  irc:
    channels:
      - "irc.freenode.org##python-code-quality"
    use_notice: true
    skip_join: true
